spring:
  application:
    name: camel-adventures-with-newrelic
  output:
    ansi:
      enabled: always

management:
  endpoint:
    shutdown:
      enabled: true
      
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8080

# logging to see the zipkin traces
logging:
  level:
    org.apache.camel.zipkin: debug
    
camel:
  zipkin:
    #endpoint: http://localhost:9411/api/v2/spans
    endpoint: https://trace-api.newrelic.com/trace/v1?X-License-Key={{YOUR_LICENSE_KEY}}&Data-Format=zipkin&Data-Format-Version=2
    include-message-body-streams: true
    service-name: preprod-camel-adventures-with-newrelic
