spring:
  application:
    name: camel-adventures-with-newrelic
  output:
    ansi:
      enabled: always

management:
  endpoint:
    shutdown:
      enabled: true
      
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8080


    
camel:
  zipkin:
    #endpoint: http://localhost:9411/api/v2/spans
    endpoint: https://trace-api.eu.newrelic.com/trace/v1?X-License-Key=eu01xx633969551abb096f8693f21d73e8b7NRAL&Data-Format=zipkin&Data-Format-Version=2
    include-message-body-streams: true
    service-name: camel-adventures-with-newrelic